{% set name = "pyvista" %}
{% set version = "0.21.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e2915a1fa8580a080a59164e724a6212e6010e009ddb02a6c2aa2d70536e882

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - imageio
    - appdirs
    - vtk
    - scooby

test:
  imports:
    - pyvista

about:
  home: https://github.com/pyvista/pyvista
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)'

  description: |
    PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK). PyVista is a helper module for the Visualization Toolkit (VTK) that takes a different approach on interfacing with VTK through NumPy and direct array access. This package provides a Pythonic, well-documented interface exposing VTK's powerful visualization backend to facilitate rapid prototyping, analysis, and visual integration of spatially referenced datasets. This module can be used for scientific plotting for presentations and research papers as well as a supporting module for other mesh dependent Python modules.
  doc_url: https://docs.pyvista.org/
  dev_url: https://github.com/pyvista/pyvista

extra:
  recipe-maintainers:
    - banesullivan
    - hadim
    - akaszynski
