{% set name = "pyvista" %}
{% set version = "0.35.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvista-{{ version }}.tar.gz
  sha256: 36e0a14ab4beac27e1e097b9c00cbb01f7af16c8b7b8ed8114f113f25790c41e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - imageio >=2.5.0
    - appdirs
    - vtk
    - scooby >=0.5.1
    - typing_extensions
    - pillow

test:
  imports:
    - pyvista
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyvista
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)

  description: |
    PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK). PyVista is a helper module for the Visualization Toolkit (VTK) that takes a different approach on interfacing with VTK through NumPy and direct array access. This package provides a Pythonic, well-documented interface exposing VTK's powerful visualization backend to facilitate rapid prototyping, analysis, and visual integration of spatially referenced datasets. This module can be used for scientific plotting for presentations and research papers as well as a supporting module for other mesh dependent Python modules.
  doc_url: https://docs.pyvista.org/
  dev_url: https://github.com/pyvista/pyvista

extra:
  recipe-maintainers:
    - banesullivan
    - akaszynski
